#!/usr/bin/env python3
"""Generate the GitHub issue forms in .github/ISSUE_TEMPLATE from shared blocks.

The platform issue forms (desktop, desktop and Android, Android, iOS) ask for
almost the same information, and GitHub issue forms have no include mechanism,
so the shared parts used to be copy-pasted into every file. Here each block is
defined once and composed per form, and `--check` (run in CI) fails when the
committed forms no longer match the generated output.

Blocks are raw YAML text rather than data structures so that the output stays
readable and byte-for-byte predictable (issue forms rely on significant
trailing whitespace in prefilled values).
"""

import argparse
import sys
from pathlib import Path

ISSUE_TEMPLATE_DIR = Path(__file__).resolve().parent.parent / '.github' / 'ISSUE_TEMPLATE'

DOCS_URL = ('https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues'
            '-and-pull-requests/syntax-for-issue-forms')

ISSUES_URL = 'https://github.com/brave/brave-browser/issues'


def header(*, name, description, labels, title=None, assignees=None):
    out = f'# {DOCS_URL}\n'
    out += f'# Generated by scripts/{Path(__file__).name} - edit that script instead.\n\n'
    out += f'name: {name}\n'
    out += f'description: {description}\n'
    out += 'labels:\n'
    for label in labels:
        out += f'  - {label}\n'
    if title is not None:
        out += f'title: {title}\n'
    if assignees is not None:
        out += 'assignees:\n'
        for assignee in assignees:
            out += f'  - {assignee}\n'
    return out + 'body:\n'


def search_prompt(*labels):
    query = '+'.join(['is%3Aissue', 'is%3Aopen'] + [f'label%3A{label}' for label in labels])
    return f'''  - type: markdown
    attributes:
      value: |-
        Have you searched for similar [issues]({ISSUES_URL}?q={query})?

        Insufficiently described issues will be closed, so please provide as much information as possible
'''


def description(what='issue'):
    return f'''  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the {what}
    validations:
      required: true
'''


STEPS_TO_REPRODUCE = '''  - type: textarea
    id: str
    attributes:
      label: Steps to reproduce
      description: A series of steps to reproduce the issue
      value: |-
        1. 
        2. 
        3. 
    validations:
      required: true
'''

RESULTS = '''  - type: textarea
    id: result
    attributes:
      label: Actual result
      description: What happened
      placeholder: include screenshots if needed
    validations:
      required: true
  - type: textarea
    id: expectation
    attributes:
      label: Expected result
      description: What should've happened
      placeholder: include screenshots if needed
    validations:
      required: true
'''

REPRODUCES_HOW_OFTEN = '''  - type: dropdown
    id: reproduces
    attributes:
      label: Reproduces how often
      multiple: false
      options:
        - Easily reproduced
        - Intermittent issue
        - No steps to reproduce
      default: 0
    validations:
      required: true
'''

BRAVE_VERSION_SIMPLE = '''  - type: textarea
    id: version
    attributes:
      label: Brave version
    validations:
      required: true
'''


def brave_version_from_about_page(label):
    return f'''  - type: textarea
    id: version
    attributes:
      label: {label} (brave://version info)
      description: "`Brave`, `Revision` and `OS` from `brave://version`"
    validations:
      required: true
'''


def android_device(label):
    return f'''  - type: textarea
    id: device
    attributes:
      label: {label}
      description: Device information
      value: |-
        - Brand/model: 
        - Android version: 
    validations:
      required: true
'''


IOS_DEVICE = '''  - type: textarea
    id: device
    attributes:
      label: Device/iOS version
    validations:
      required: true
'''

CHANNELS = '''  - type: checkboxes
    id: channels
    attributes:
      label: Channel information
      description: Which browser channels does this issue occur on
      options:
        - label: release (stable)
        - label: beta
        - label: nightly
'''

IOS_AFFECTED_VERSIONS = '''  - type: checkboxes
    id: affected
    attributes:
      label: Affected browser versions
      description: Which browser versions does this issue occur on
      options:
        - label: latest AppStore
        - label: latest TestFlight
        - label: previous TestFlight
'''


def reproducibility(*options):
    out = '''  - type: checkboxes
    id: reproducibility
    attributes:
      label: Reproducibility
      description: Does this issue occur...
      options:
'''
    for option in options:
        out += f'        - label: {option}\n'
    return out


DEFAULT_REPRODUCIBILITY = reproducibility('with Brave Shields disabled',
                                          'with Brave Rewards disabled',
                                          'in the latest version of Chrome')

MISC = '''  - type: textarea
    id: misc
    attributes:
      label: Miscellaneous information
      description: Any additional information, related issues, extra QA steps, configuration or data that might be necessary to reproduce the issue
'''


def bug_report(*, name, issue_description, labels, search_labels, version, device=None,
               versions_block=CHANNELS, reproducibility_block=DEFAULT_REPRODUCIBILITY):
    return ''.join([
        header(name=name, description=issue_description, labels=labels),
        search_prompt(*search_labels),
        description(),
        STEPS_TO_REPRODUCE,
        RESULTS,
        REPRODUCES_HOW_OFTEN,
        version,
        device or '',
        versions_block,
        reproducibility_block,
        MISC,
    ])


TEMPLATES = {
    '01_desktop.yml': bug_report(
        name='Desktop issue',
        issue_description='An issue affecting Linux, macOS, or Windows',
        labels=['OS/Desktop'],
        search_labels=['OS%2FDesktop'],
        version=brave_version_from_about_page('Brave version'),
    ),
    '02_desktop_and_android.yml': bug_report(
        name='Desktop and Android issue',
        issue_description='An issue affecting Android and Linux, macOS, or Windows',
        labels=['OS/Android', 'OS/Desktop'],
        search_labels=['OS%2FDesktop', 'OS%2FAndroid'],
        version=brave_version_from_about_page('Desktop Brave version'),
        device=android_device('Android device'),
    ),
    '03_android.yml': bug_report(
        name='Android issue',
        issue_description='An issue affecting Android',
        labels=['OS/Android'],
        search_labels=['OS%2FAndroid'],
        version=BRAVE_VERSION_SIMPLE,
        device=android_device('Device'),
    ),
    '04_ios.yml': bug_report(
        name='iOS issue',
        issue_description='An issue affecting iOS',
        labels=['OS/iOS'],
        search_labels=['OS%2FiOS'],
        version=BRAVE_VERSION_SIMPLE,
        device=IOS_DEVICE,
        versions_block=IOS_AFFECTED_VERSIONS,
        reproducibility_block=reproducibility('with Brave Shields disabled',
                                              'in the latest version of mobile Safari'),
    ),
    '05_feature_request.yml': ''.join([
        header(name='Feature request',
               description='Request a new feature',
               labels=['feature-request']),
        search_prompt('feature-request'),
        '''  - type: dropdown
    id: platforms
    attributes:
      label: Platforms
      multiple: true
      options:
        - all
        - Android
        - iOS
        - Linux
        - macOS
        - Windows
      default: 0
    validations:
      required: true
''',
        description('feature'),
    ]),
    '06_chromium_bump.yml': ''.join([
        header(name='Chromium minor bump',
               description='An issue for a minor Chromium bump',
               labels=['Chromium/upgrade minor', 'OS/Android', 'OS/Desktop',
                       'QA/Test-Plan-Specified', 'QA/Yes', 'release-notes/include'],
               title='"Upgrade from Chromium **PREVIOUS_VERSION** to Chromium **NEW_VERSION**"',
               assignees=['emerick', 'mkarolin']),
        '''  - type: textarea
    id: bump
    attributes:
      label: Minor Chromium bump
      value: |-
        https://chromium.googlesource.com/chromium/src/+log/PREVIOUS_VERSION..NEW_VERSION?pretty=fuller&n=10000
    validations:
      required: true
  - type: textarea
    id: qa
    attributes:
      label: QA tests
      value: |-
        - Check branding items
        - Check for version bump
    validations:
      required: true
  - type: textarea
    id: checks
    attributes:
      label: Minor Chromium bump
      value: |-
        - No specific code changes in Brave (only line number changes in patches)
''',
    ]),
    '07_code_health.yml': ''.join([
        header(name='Code health',
               description='Follow ups for open pull requests, refactoring, dependency updates',
               labels=['dev-concern']),
        search_prompt('dev-concern'),
        description(),
    ]),
}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true',
                        help='exit non-zero when the committed forms are out of date')
    args = parser.parse_args()

    outdated = []
    for filename, content in TEMPLATES.items():
        path = ISSUE_TEMPLATE_DIR / filename
        if args.check:
            if not path.exists() or path.read_text() != content:
                outdated.append(filename)
        else:
            path.write_text(content)

    if outdated:
        print('Out of date issue forms: {}\nRun scripts/{} to regenerate them.'.format(
            ', '.join(sorted(outdated)), Path(__file__).name), file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
